apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus
spec:
  template:
    spec:
      containers:
      - name: janus
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_SECRET_KEY